
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rssagg
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: fursovych20@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin



  app:
    build: .
    container_name: app
    env_file:
      - .env
    depends_on:
      - postgres
      - migrate
    ports:
      - "8082:8082"

  migrate:
    container_name: migrate
    build:
      context: .
      target: builder
    working_dir: /app
    command: ./run_goose.sh
    depends_on:
      - postgres


volumes:
  db_data:
  pgadmin-data: