version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: rssagg_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: rssagg
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: fursovych20@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin



#  app:
#    build: .
#    env_file:
#      - .env
#    depends_on:
#      - db
#    ports:
#      - "8082:8082"

volumes:
  db_data:
  pgadmin-data: