// Code generated by MockGen. DO NOT EDIT.
// Source: feed_service.go
//
// Generated by this command:
//
//	mockgen -source=feed_service.go -destination=../../test/usecase/feed_service_test.go -package=usecase interfaces.FeedServiceInterface,interfaces.FeedRepository,interfaces.UserRepository
//

// Package usecase is a generated GoMock package.
package usecase
