// Code generated by MockGen. DO NOT EDIT.
// Source: user_service.go
//
// Generated by this command:
//
//	mockgen -source=user_service.go -destination=../../test/usecase/user_service_test.go -package=usecase interfaces.UserRepository
//

// Package usecase is a generated GoMock package.
package usecase
